### ISSUE TITLE
Heroku Deploy errors and failure

### ISSUE THREAD

**Issue by mathewgj** [juliocesar/shining#6]
My terminal output - what do you guess is happening here?:

$ shine deploy
Invalid gemspec in [/Library/Ruby/Gems/1.8/specifications/heroku-2.16.2.gemspec]: invalid date format in specification: "2011-12-13 00:00:00.000000000Z"
Invalid gemspec in [/Library/Ruby/Gems/1.8/specifications/term-ansicolor-1.0.7.gemspec]: invalid date format in specification: "2011-10-13 00:00:00.000000000Z"
Enter your Heroku credentials.
/Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/helpers.rb:74:in `gets': No such file or directory - deploy (Errno::ENOENT)
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/helpers.rb:74:in`ask'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/commands/auth.rb:68:in `ask_for_credentials'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/commands/auth.rb:46:in`get_credentials'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/commands/auth.rb:30:in `user'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/commands/auth.rb:10:in`init_heroku'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/commands/auth.rb:6:in `client'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/command.rb:48:in`send'
    from /Library/Ruby/Gems/1.8/gems/heroku-1.15.1/lib/heroku/command.rb:48:in `run_internal'
    from /Library/Ruby/Gems/1.8/gems/shining-2.0.1/bin/../lib/shining/heroku.rb:14:in`initialize'
    from /Library/Ruby/Gems/1.8/gems/shining-2.0.1/bin/shine:69:in `new'
    from /Library/Ruby/Gems/1.8/gems/shining-2.0.1/bin/shine:69:in`deploy'
    from /Library/Ruby/Gems/1.8/gems/shining-2.0.1/bin/shine:28:in `send'
    from /Library/Ruby/Gems/1.8/gems/shining-2.0.1/bin/shine:28:in`figure_what_to_do!'
    from /Library/Ruby/Gems/1.8/gems/shining-2.0.1/bin/shine:90
    from /usr/bin/shine:19:in `load'
    from /usr/bin/shine:19
$

**Comment by jim0thy** [comment]
The instructions here fixed it for me.
http://stackoverflow.com/questions/5771758/invalid-gemspec-because-of-the-date-format-in-specification
